"""CID-3 — the JS code-unit legacy hash, validated against the real implementation.

The spec says of the historical shapes: *"Call the exported functions; do not
reimplement them."* No non-JS lane can. The blessed substitute is **execution
validation**: generate vectors by running the reference implementation, pin them, and
pin the property that distinguishes a correct port from a plausible one.

`tests/fixtures/legacy-custom-id-reference.json` was produced by executing
``generateLegacyCustomId`` / ``md5Core`` from ``langsys-js-typescript`` ``src/utils.ts``
and ``src/content-block.ts`` — not transcribed, and not computed by this SDK. It is a
shared contract artifact: its home will be ``langsys-php/tests/fixtures/`` beside
``custom-id-reference.json``. **Lifters should pin its git blob SHA, not this path.**

The distinguishing property matters more than the row count. An MD5 fed UTF-16 code
units agrees with a byte-based one across all of ASCII and diverges everywhere above
it, so a port that silently became a byte hash passes every ASCII row. The
divergence rows below are what make that port fail.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from langsys.registration import _md5_utf16_code_units, legacy_custom_ids

FIXTURE = Path(__file__).parent / "fixtures" / "legacy-custom-id-reference.json"

#: THE CHECK — content-addressed, verified locally with no network.
SOURCE_BLOB_SHA = "dc5556466dc54fe82e81ac9fdbf4549b2b76e7ce"
#: THE PROVENANCE — generated by executing langsys-js-typescript src/utils.ts md5Core
#: and src/content-block.ts generateLegacyCustomId (node v22).
SOURCE_REF = "langsys-js-typescript src/utils.ts::md5Core @ 6cdb388"

ROWS = json.loads(FIXTURE.read_text(encoding="utf-8"))


def _git_blob_sha(data: bytes) -> str:
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()  # noqa: S324


def test_the_vector_file_is_the_pinned_blob():
    assert _git_blob_sha(FIXTURE.read_bytes()) == SOURCE_BLOB_SHA, (
        f"legacy vector file no longer matches {SOURCE_BLOB_SHA} (from {SOURCE_REF}). "
        "Regenerate by executing the JS implementation; never hand-edit."
    )


@pytest.mark.parametrize("row", ROWS, ids=lambda r: r["canonical_json"][:36])
def test_codepoints_first_inputs_survived(row):
    def rebuild(points):
        return "".join(chr(int(p[2:], 16)) for p in points)

    if row["codepoints"]["category"] is not None:
        assert rebuild(row["codepoints"]["category"]) == row["category"]
    assert [rebuild(p) for p in row["codepoints"]["tokens"]] == row["tokens"]


@pytest.mark.parametrize("row", ROWS, ids=lambda r: r["canonical_json"][:36])
def test_the_port_matches_the_real_js_implementation(row):
    assert _md5_utf16_code_units(row["canonical_json"]) == row["legacy_custom_id"]


def test_the_port_is_not_secretly_a_byte_hash():
    """The distinguishing property. Without this, every ASCII row passes against a
    plain UTF-8 md5 and the suite certifies a port that is wrong above Latin-1."""
    agree = disagree = 0
    for row in ROWS:
        js = row["legacy_custom_id"]
        byte_hash = hashlib.md5(row["canonical_json"].encode("utf-8")).hexdigest()  # noqa: S324
        if js == byte_hash:
            agree += 1
        else:
            disagree += 1
    assert agree, "no ASCII row agrees — the vectors cannot show the equivalence"
    assert disagree, (
        "no row diverges from a UTF-8 byte hash: these vectors cannot distinguish a "
        "code-unit port from a byte-hash port, which is the only thing they exist to do"
    )


def test_the_documented_code_unit_collision_reproduces():
    """`["UI",["xxxA"]]` and `["UI",["xxxŁ"]]` hash identically — the UTF-16 packing
    loses a byte at every fourth position. This is why an old id does not identify one
    block, and why re-keying stored rows is prohibited rather than merely discouraged."""
    a = next(r for r in ROWS if r["canonical_json"] == '["UI",["xxxA"]]')
    b = next(r for r in ROWS if r["canonical_json"] == '["UI",["xxxŁ"]]')
    assert a["legacy_custom_id"] == b["legacy_custom_id"]
    assert _md5_utf16_code_units(a["canonical_json"]) == _md5_utf16_code_units(
        b["canonical_json"]
    )


def test_the_documented_pipe_collision_reproduces():
    """Category `UI|Buy now` with no phrases collides with category `UI` and phrase
    `Buy now`: joining on an unescaped delimiter loses the field boundary. Belongs to
    the pipe scheme, not the JSON one — the two collision modes are different."""
    a = next(r for r in ROWS if r["canonical_json"] == '["UI|Buy now",[]]')
    b = next(r for r in ROWS if r["canonical_json"] == '["UI",["Buy now"]]')
    assert a["pipe_join_custom_id"] == b["pipe_join_custom_id"]
    # ...and they do NOT collide under the JSON-based code-unit scheme.
    assert a["legacy_custom_id"] != b["legacy_custom_id"]


def test_both_uncategorised_spellings_are_offered_on_lookup():
    """Tolerance must not normalise its inputs: the old paths did not, so both slots
    have to be tried. This is the breadth check, at the id-list level."""
    ids = legacy_custom_ids(None, ["Hello", "World"])
    empty = next(r for r in ROWS if r["canonical_json"] == '["",["Hello","World"]]')
    sentinel = next(
        r for r in ROWS if r["canonical_json"] == '["__uncategorized__",["Hello","World"]]'
    )
    assert empty["legacy_custom_id"] in ids
    assert sentinel["legacy_custom_id"] in ids
    assert empty["pipe_join_custom_id"] in ids
    assert sentinel["pipe_join_custom_id"] in ids
